export const designTokens = {
  spacing: {
    none: "0",
    xxs: "0.125rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    xxl: "2rem",
    "3xl": "3rem",
    "4xl": "4rem",
    "5xl": "6rem",
    "6xl": "8rem",
  },
  fontSize: {
    xs: "0.75rem",
    sm: "0.875rem",
    md: "1rem",
    lg: "1.125rem",
    xl: "1.25rem",
    "2xl": "1.5rem",
    "3xl": "2rem",
    "4xl": "2.5rem",
    "5xl": "3rem",
    "6xl": "4rem",
    "7xl": "5rem",
  },
  lineHeight: {
    tight: 1.1,
    compact: 1.25,
    normal: 1.5,
    relaxed: 1.7,
    loose: 1.9,
  },
  fontWeight: {
    regular: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
  },
  radius: {
    none: "0",
    sm: "0.25rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
    pill: "9999px",
    round: "50%",
  },
  borderWidth: {
    thin: "1px",
    regular: "2px",
    strong: "3px",
    heavy: "0.25rem",
  },
  size: {
    iconSm: "1rem",
    iconMd: "1.5rem",
    iconLg: "2rem",
    controlSm: "2rem",
    controlMd: "2.5rem",
    controlLg: "3rem",
    brandLogo: "6.25rem",
    contentMax: "87.5rem",
    proseMax: "46rem",
    pageMinHeight: "90vh",
    heroHeight: "35rem",
    cardHeight: "12rem",
    imageRailWidth: "24rem",
  },
  duration: {
    instant: "0ms",
    fast: "120ms",
    normal: "220ms",
    slow: "320ms",
    slower: "500ms",
    spin: "12s",
  },
  easing: {
    standard: "ease",
    in: "ease-in",
    out: "ease-out",
    inOut: "ease-in-out",
  },
  shadow: {
    none: "none",
    sm: "0 1px 2px rgba(0, 0, 0, 0.12)",
    md: "0 8px 20px rgba(0, 0, 0, 0.16)",
    lg: "0 14px 32px rgba(0, 0, 0, 0.2)",
  },
  zIndex: {
    base: 0,
    raised: 1,
    overlay: 10,
    modal: 20,
    popover: 30,
    toast: 40,
  },
  breakpoint: {
    xs: "360px",
    sm: "600px",
    md: "768px",
    lg: "992px",
    xl: "1200px",
    xxl: "1440px",
  },
};

export const media = {
  xs: `@media (min-width: ${designTokens.breakpoint.xs})`,
  sm: `@media (min-width: ${designTokens.breakpoint.sm})`,
  md: `@media (min-width: ${designTokens.breakpoint.md})`,
  lg: `@media (min-width: ${designTokens.breakpoint.lg})`,
  xl: `@media (min-width: ${designTokens.breakpoint.xl})`,
  xxl: `@media (min-width: ${designTokens.breakpoint.xxl})`,
};

export const layoutBreakpoint = {
  headerDesktop: designTokens.breakpoint.lg,
} as const;

export const layoutMedia = {
  headerDesktop: `@media (min-width: ${layoutBreakpoint.headerDesktop})`,
};
